using System.Collections.Generic;

public static class BibleBookMap
{
  public static readonly Dictionary<string, string> Map = new()
  {
    { "Genesis", "Genesis" },
    { "Exodus", "Exodus" },
    { "Leviticus", "Leviticus" },
    { "Numbers", "Numbers" },
    { "Deuteronomy", "Deuteronomy" },
    { "Joshua", "Joshua" },
    { "Judges", "Judges" },
    { "Ruth", "Ruth" },
    { "1 Samuel", "1 Samuel" },
    { "I Samuel", "1 Samuel" },
    { "2 Samuel", "2 Samuel" },
    { "II Samuel", "2 Samuel" },
    { "1 Kings", "1 Kings" },
    { "I Kings", "1 Kings" },
    { "2 Kings", "2 Kings" },
    { "II Kings", "2 Kings" },
    { "1 Chronicles", "1 Chronicles" },
    { "I Chronicles", "1 Chronicles" },
    { "2 Chronicles", "2 Chronicles" },
    { "II Chronicles", "2 Chronicles" },
    { "Ezra", "Ezra" },
    { "Nehemiah", "Nehemiah" },
    { "Esther", "Esther" },
    { "Job", "Job" },
    { "Psalms", "Psalms" },
    { "Proverbs", "Proverbs" },
    { "Ecclesiastes", "Ecclesiastes" },
    { "Song of Solomon", "Song of Solomon" },
    { "Song of Songs", "Song of Solomon" },
    { "The Song of Solomon", "Song of Solomon" },
    { "Canticles", "Song of Solomon" },
    { "Isaiah", "Isaiah" },
    { "Jeremiah", "Jeremiah" },
    { "Lamentations", "Lamentations" },
    { "Ezekiel", "Ezekiel" },
    { "Daniel", "Daniel" },
    { "Hosea", "Hosea" },
    { "Joel", "Joel" },
    { "Amos", "Amos" },
    { "Obadiah", "Obadiah" },
    { "Jonah", "Jonah" },
    { "Micah", "Micah" },
    { "Nahum", "Nahum" },
    { "Habakkuk", "Habakkuk" },
    { "Zephaniah", "Zephaniah" },
    { "Haggai", "Haggai" },
    { "Zechariah", "Zechariah" },
    { "Malachi", "Malachi" },
    { "Matthew", "Matthew" },
    { "Mark", "Mark" },
    { "Luke", "Luke" },
    { "John", "John" },
    { "Acts", "Acts" },
    { "Romans", "Romans" },
    { "1 Corinthians", "1 Corinthians" },
    { "I Corinthians", "1 Corinthians" },
    { "2 Corinthians", "2 Corinthians" },
    { "II Corinthians", "2 Corinthians" },
    { "Galatians", "Galatians" },
    { "Ephesians", "Ephesians" },
    { "Philippians", "Philippians" },
    { "Colossians", "Colossians" },
    { "1 Thessalonians", "1 Thessalonians" },
    { "I Thessalonians", "1 Thessalonians" },
    { "2 Thessalonians", "2 Thessalonians" },
    { "II Thessalonians", "2 Thessalonians" },
    { "1 Timothy", "1 Timothy" },
    { "I Timothy", "1 Timothy" },
    { "2 Timothy", "2 Timothy" },
    { "II Timothy", "2 Timothy" },
    { "Titus", "Titus" },
    { "Philemon", "Philemon" },
    { "Hebrews", "Hebrews" },
    { "James", "James" },
    { "1 Peter", "1 Peter" },
    { "I Peter", "1 Peter" },
    { "2 Peter", "2 Peter" },
    { "II Peter", "2 Peter" },
    { "1 John", "1 John" },
    { "I John", "1 John" },
    { "2 John", "2 John" },
    { "II John", "2 John" },
    { "3 John", "3 John" },
    { "III John", "3 John" },
    { "Jude", "Jude" },
    { "Revelation", "Revelation" },
    { "Revelation of John", "Revelation" },
    { "The Revelation", "Revelation" },
    { "Revelation of Jesus Christ", "Revelation" }
  };
}